server:
  port: 9002

spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.87.176:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
